import { isTextDocument, MAX_TEXT_DOCUMENT_BYTES } from "./document-text.ts";
import { isDocxDocument, MAX_DOCX_INPUT } from "./docx-ingest.ts";
import { isPdfDocument, MAX_PDF_BYTES } from "./pdf-ingest.ts";
import { CONFIGURATION_ERROR_CODE, CONFIGURATION_ERROR_MESSAGE } from "../supabase/network-policy.ts";
export type Conversation = {
  id: string;
  title: string;
  pinned: boolean;
  archived: boolean;
  selected_model: string;
  updated_at: string;
  temporary: boolean;
};
export type Message = {
  id: string;
  conversation_id: string;
  role: "user" | "assistant" | "system";
  content: string;
  model: string | null;
  status: string;
  created_at: string;
  metadata?: Record<string, unknown>;
};
export const AI_FUNCTION =
  process.env.NEXT_PUBLIC_NOATA_AI_FUNCTION || "noata-ai-v2";
export const TOOLS = [
  {
    action: "image",
    label: "ارسم فكرة",
    description: "إنشاء صورة",
    icon: "image",
  },
  {
    action: "translate",
    label: "ترجم النص",
    description: "العربية والإنجليزية",
    icon: "book",
  },
  {
    action: "poem",
    label: "اكتب شعرًا",
    description: "صياغة عربية إبداعية",
    icon: "edit",
  },
  {
    action: "moderate",
    label: "راجع المحتوى",
    description: "مراجعة ملاءمة النص",
    icon: "check",
  },
  {
    action: "sadiq_validate",
    label: "تحقّق من معلومة",
    description: "تحقّق بالمساعد صادق",
    icon: "search",
  },
  {
    action: "sadiq_research",
    label: "ابحث بتعمّق",
    description: "بحث بالمساعد صادق",
    icon: "book",
  },
];
export function titleFrom(text: string) {
  const clean = text.trim().replace(/\s+/g, " ");
  return clean.length > 48 ? clean.slice(0, 48) + "…" : clean || "محادثة جديدة";
}
export function validateAttachment(file: {
  name: string;
  type: string;
  size: number;
}) {
  if (isPdfDocument(file)) {
    if (!file.size) return "الملف فارغ.";
    return file.size <= MAX_PDF_BYTES
      ? ""
      : "الحد الأقصى لملفات PDF هو 8 ميجابايت.";
  }
  if (isDocxDocument(file)) {
    if (file.size === 0) return "الملف فارغ. اختار ملف تاني.";
    return file.size <= MAX_DOCX_INPUT
      ? ""
      : "ملفات Word الحد الأقصى لها 6 ميجابايت.";
  }
  if (isTextDocument(file)) {
    if (!file.size) return "الملف فارغ. اختار ملف تاني.";
    return file.size <= MAX_TEXT_DOCUMENT_BYTES
      ? ""
      : "الملفات النصية حدها 512 كيلوبايت. اختار ملف أصغر.";
  }
  if (
    ![
      "image/png",
      "image/jpeg",
      "image/webp",
      "audio/webm",
      "audio/ogg",
      "audio/mp4",
      "audio/mpeg",
      "audio/wav",
    ].includes(file.type.split(";")[0])
  )
    return "المدعوم حاليًا: PNG/JPG/WebP أو صوت، ومستندات TXT/MD/CSV/JSON/DOCX/PDF. الملفات المصورة قد تحتاج OCR غير متاح حاليًا.";
  if (file.size > 10 * 1024 * 1024)
    return "حجم الملف لازم يكون أقل من 10 ميجابايت.";
  if (file.size === 0) return "الملف فارغ. اختار ملف تاني.";
  return "";
}
/**
 * Only allow temporary private-upload links generated by our own Supabase storage.
 * Historical message metadata must never inject an external download target.
 */
export function safeStorageLink(
  link: unknown,
  supabaseOrigin: string,
  bucket:
    | "noata-uploads"
    | "noata-documents"
    | "noata-generated" = "noata-uploads",
): string | null {
  if (typeof link !== "string") return null;
  try {
    const candidate = new URL(link);
    if (candidate.protocol !== "https:" || candidate.username || candidate.password || candidate.hash) return null;
    if (candidate.origin !== new URL(supabaseOrigin).origin) return null;
    if (
      !candidate.pathname.startsWith("/storage/v1/object/sign/" + bucket + "/")
    )
      return null;
    return candidate.href;
  } catch {
    return null;
  }
}
export function safeHref(href: string | null) {
  if (
    !href ||
    !href.startsWith("/") ||
    href.startsWith("//") ||
    /[\\\u0000-\u0020\u007f]/.test(href)
  )
    return "/notifications";
  try {
    return new URL(href, "https://noata.invalid").origin ===
      "https://noata.invalid"
      ? href
      : "/notifications";
  } catch {
    return "/notifications";
  }
}
export function parseStreamFrames(buffer: string) {
  const normalized = buffer.replace(/\r\n/g, "\n");
  const blocks = normalized.split("\n\n");
  const rest = blocks.pop() ?? "";
  const data = blocks
    .flatMap((block) =>
      block
        .split("\n")
        .filter((line) => line.startsWith("data:"))
        .map((line) => line.slice(5).trim()),
    )
    .filter(Boolean);
  return { data, rest };
}
/** Translate a provider HTTP failure into a stable, non-sensitive UI error. */
export function aiResponseFailure(status: number, body: unknown): string {
  const value = body && typeof body === "object" ? (body as Record<string, unknown>) : {};
  if (value.code === CONFIGURATION_ERROR_CODE) return CONFIGURATION_ERROR_CODE;
  if (status === 503 &&
      (value.code === "FANAR_NOT_CONFIGURED" ||
       value.error === "AI backend is not configured"))
    return "FANAR_NOT_CONFIGURED";
  if (status === 503) return "FANAR_UNAVAILABLE";
  return String(status);
}

export function friendlyError(error: unknown) {
  const message = error instanceof Error ? error.message : String(error);
  if (message.includes(CONFIGURATION_ERROR_CODE)) return CONFIGURATION_ERROR_MESSAGE;
  if (message.includes("FANAR_NOT_CONFIGURED"))
    return "مساعد Noata AI غير متاح في بيئة الاختبار حاليًا لأن ربط Fanar لم يكتمل بعد. لم تُرسل رسالتك إلى النموذج؛ احتفظ بها لحين تفعيل الخدمة.";
  if (/FANAR_UNAVAILABLE|\b503\b/.test(message))
    return "خدمة Fanar غير متاحة مؤقتًا. لم نتمكن من إكمال الرد؛ حاول لاحقًا.";
  if (/429|quota|rate/i.test(message))
    return "وصلت لحد الاستخدام الحالي. جرّب بعد شوية.";
  if (/401|jwt|sign in|auth|session/i.test(message))
    return "الجلسة انتهت. سجّل الدخول تاني علشان نكمل.";
  if (/abort/i.test(message))
    return "تم إيقاف الطلب. تقدر تكمّل أو تحاول تاني.";
  if (/timeout|timed out/i.test(message))
    return "الرد أخد وقت أطول من المتوقع. حاول تاني.";
  return "تعذّر إكمال الطلب. راجع اتصالك وحاول تاني. انسخ أي نص مهم قبل المغادرة.";
}
