import { isTextDocument, MAX_TEXT_DOCUMENT_BYTES } from "./document-text.ts";
import { isDocxDocument, MAX_DOCX_INPUT } from "./docx-ingest.ts";
import { isPdfDocument, MAX_PDF_BYTES } from "./pdf-ingest.ts";
export type Conversation = {
  id: string;
  title: string;
  pinned: boolean;
  archived: boolean;
  selected_model: string;
  updated_at: string;
  temporary: boolean;
};
export type Message = {
  id: string;
  conversation_id: string;
  role: "user" | "assistant" | "system";
  content: string;
  model: string | null;
  status: string;
  created_at: string;
  metadata?: Record<string, unknown>;
};
export const AI_FUNCTION =
  process.env.NEXT_PUBLIC_NOATA_AI_FUNCTION || "noata-ai-v2";
export const TOOLS = [
  {
    action: "image",
    label: "ارسم فكرة",
    description: "إنشاء صورة",
    icon: "image",
  },
  {
    action: "translate",
    label: "ترجم النص",
    description: "العربية والإنجليزية",
    icon: "book",
  },
  {
    action: "poem",
    label: "اكتب شعرًا",
    description: "صياغة عربية إبداعية",
    icon: "edit",
  },
  {
    action: "moderate",
    label: "راجع المحتوى",
    description: "مراجعة ملاءمة النص",
    icon: "check",
  },
  {
    action: "sadiq_validate",
    label: "تحقّق من معلومة",
    description: "تحقّق بالمساعد صادق",
    icon: "search",
  },
  {
    action: "sadiq_research",
    label: "ابحث بتعمّق",
    description: "بحث بالمساعد صادق",
    icon: "book",
  },
];
export function titleFrom(text: string) {
  const clean = text.trim().replace(/\s+/g, " ");
  return clean.length > 48 ? clean.slice(0, 48) + "…" : clean || "محادثة جديدة";
}
export function validateAttachment(file: {
  name: string;
  type: string;
  size: number;
}) {
  if (isPdfDocument(file)) {
    if (!file.size) return "الملف فارغ.";
    return file.size<=MAX_PDF_BYTES ? "" : "الحد الأقصى لملفات PDF هو 8 ميجابايت.";
  }
  if (isDocxDocument(file)) {
    if (file.size === 0) return "الملف فارغ. اختار ملف تاني.";
    return file.size <= MAX_DOCX_INPUT ? "" : "ملفات Word الحد الأقصى لها 6 ميجابايت.";
  }
  if (isTextDocument(file)) {
    if (!file.size) return "الملف فارغ. اختار ملف تاني.";
    return file.size <= MAX_TEXT_DOCUMENT_BYTES
      ? ""
      : "الملفات النصية حدها 512 كيلوبايت. اختار ملف أصغر.";
  }
  if (
    ![
      "image/png",
      "image/jpeg",
      "image/webp",
      "audio/webm",
      "audio/ogg",
      "audio/mp4",
      "audio/mpeg",
      "audio/wav",
    ].includes(file.type.split(";")[0])
  )
    return "المدعوم حاليًا: PNG/JPG/WebP أو صوت، ومستندات TXT/MD/CSV/JSON/DOCX/PDF. الملفات المصورة قد تحتاج OCR غير متاح حاليًا.";
  if (file.size > 10 * 1024 * 1024)
    return "حجم الملف لازم يكون أقل من 10 ميجابايت.";
  if (file.size === 0) return "الملف فارغ. اختار ملف تاني.";
  return "";
}
/**
 * Only allow temporary private-upload links generated by our own Supabase storage.
 * Historical message metadata must never inject an external download target.
 */
export function safeStorageLink(link: unknown, supabaseOrigin: string): string | null {
  if (typeof link !== "string") return null;
  try {
    const candidate = new URL(link);
    if (candidate.protocol !== "https:") return null;
    if (candidate.origin !== new URL(supabaseOrigin).origin) return null;
    if (!candidate.pathname.startsWith("/storage/v1/object/sign/noata-uploads/")) return null;
    return candidate.href;
  } catch {
    return null;
  }
}
export function safeHref(href: string | null) {
  return href &&
    href.startsWith("/") &&
    !href.startsWith("//") &&
    !href.includes("\\")
    ? href
    : "/notifications";
}
export function parseStreamFrames(buffer: string) {
  const normalized = buffer.replace(/\r\n/g, "\n");
  const blocks = normalized.split("\n\n");
  const rest = blocks.pop() ?? "";
  const data = blocks
    .flatMap((block) =>
      block
        .split("\n")
        .filter((line) => line.startsWith("data:"))
        .map((line) => line.slice(5).trim()),
    )
    .filter(Boolean);
  return { data, rest };
}
export function friendlyError(error: unknown) {
  const message = error instanceof Error ? error.message : String(error);
  if (/429|quota|rate/i.test(message))
    return "وصلت لحد الاستخدام الحالي. جرّب بعد شوية.";
  if (/401|jwt|sign in|auth|session/i.test(message))
    return "الجلسة انتهت. سجّل الدخول تاني علشان نكمل.";
  if (/abort/i.test(message))
    return "تم إيقاف الطلب. تقدر تكمّل أو تحاول تاني.";
  if (/timeout|timed out/i.test(message))
    return "الرد أخد وقت أطول من المتوقع. حاول تاني.";
  return "تعذّر إكمال الطلب. راجع اتصالك وحاول تاني. انسخ أي نص مهم قبل المغادرة.";
}
