export function createSeed() {
  return {
    meta: { schemaVersion: 1, seededAt: new Date().toISOString(), demo: true },
    users: [
      { id: 'student-1', email: 'student@demo.local', password: 'demo123', role: 'student', nameAr: 'نور أحمد', nameEn: 'Nour Ahmed', language: 'ar', avatarItemId: 'avatar-explorer' },
      { id: 'teacher-1', email: 'teacher@demo.local', password: 'demo123', role: 'teacher', nameAr: 'أستاذة سلمى', nameEn: 'Ms Salma', language: 'ar' },
      { id: 'admin-1', email: 'admin@demo.local', password: 'demo123', role: 'admin', nameAr: 'مسؤول المحتوى', nameEn: 'Content Admin', language: 'ar' },
    ],
    classes: [{ id: 'class-1', nameAr: 'مجموعة العلوم التجريبية', nameEn: 'Demo Science Group', teacherId: 'teacher-1' }],
    enrollments: [{ classId: 'class-1', studentId: 'student-1' }],
    curriculum: {
      id: 'demo-science-v1',
      version: '1.0-demo',
      titleAr: 'علوم تجريبية — محتوى توضيحي',
      titleEn: 'Demo Science — Illustrative content',
      gradeAr: 'مرحلة ثانوية — غير معتمد',
      gradeEn: 'Secondary level — not approved',
      provenance: 'Original demonstration content created for product testing. Not aligned to an official syllabus.',
      status: 'published-demo',
      units: [
        {
          id: 'unit-motion', titleAr: 'الحركة والتمثيل البياني', titleEn: 'Motion and graphs', order: 1,
          descriptionAr: 'اقرأ الحركة من المسافة والزمن، ثم استخدم الأدلة لتفسيرها.',
          descriptionEn: 'Read motion from distance and time, then explain it with evidence.',
          lessons: [
            { id: 'lesson-motion-basics', titleAr: 'ما معنى السرعة؟', titleEn: 'What does speed mean?', order: 1, duration: 7, skills: ['skill-speed'],
              summaryAr: 'السرعة تصف مقدار المسافة المقطوعة في وحدة زمن. السرعة المتوسطة = المسافة ÷ الزمن.',
              summaryEn: 'Speed describes distance travelled per unit of time. Average speed = distance ÷ time.',
              workedAr: 'قطع درّاج 120 مترًا في 20 ثانية. السرعة المتوسطة = 120 ÷ 20 = 6 م/ث.',
              workedEn: 'A cyclist covers 120 m in 20 s. Average speed = 120 ÷ 20 = 6 m/s.',
              questionIds: ['q-speed-1', 'q-speed-2', 'q-speed-3'] },
            { id: 'lesson-graphs', titleAr: 'احكِ قصة الرسم', titleEn: 'Tell the graph’s story', order: 2, duration: 8, skills: ['skill-graphs'], prerequisiteId: 'lesson-motion-basics',
              summaryAr: 'في رسم المسافة–الزمن، الميل الأكبر يعني سرعة أكبر، والخط الأفقي يعني أن الجسم متوقف.',
              summaryEn: 'On a distance–time graph, a steeper slope means greater speed; a horizontal line means stopped.',
              workedAr: 'إذا ظلت المسافة 40 مترًا من الثانية 5 إلى 8، فالجسم لم يتحرك خلال هذه الفترة.',
              workedEn: 'If distance stays at 40 m from second 5 to 8, the object did not move in that interval.',
              questionIds: ['q-graph-1', 'q-graph-2', 'q-graph-3'] },
          ],
          bossQuestionIds: ['q-boss-1', 'q-boss-2', 'q-boss-3'],
        },
        {
          id: 'unit-forces', titleAr: 'القوى والتغيّر', titleEn: 'Forces and change', order: 2,
          descriptionAr: 'وحدة تجريبية قيد المراجعة وغير متاحة بعد.', descriptionEn: 'A demo unit under review and not yet available.',
          locked: true, lessons: [], bossQuestionIds: [],
        },
      ],
    },
    skills: [
      { id: 'skill-speed', titleAr: 'حساب السرعة المتوسطة', titleEn: 'Calculate average speed' },
      { id: 'skill-graphs', titleAr: 'تفسير رسوم الحركة', titleEn: 'Interpret motion graphs' },
    ],
    questions: [
      { id: 'q-speed-1', version: 1, lessonId: 'lesson-motion-basics', skillId: 'skill-speed', difficulty: 'core', type: 'multiple-choice', promptAr: 'قطع عدّاء 100 متر في 20 ثانية. ما سرعته المتوسطة؟', promptEn: 'A runner covers 100 m in 20 s. What is the average speed?', choicesAr: ['2 م/ث', '5 م/ث', '20 م/ث', '80 م/ث'], choicesEn: ['2 m/s', '5 m/s', '20 m/s', '80 m/s'], correctAnswer: '1', explanationAr: 'نقسم المسافة على الزمن: 100 ÷ 20 = 5 م/ث.', explanationEn: 'Divide distance by time: 100 ÷ 20 = 5 m/s.', distractorFeedback: { '0': 'قرّب الفكرة: اقسم المسافة على الزمن، ولا تطرح بينهما.', '2': '20 هو الزمن، وليس السرعة. استخدم 100 ÷ 20.', '3': 'طرح الزمن من المسافة لا يعطينا السرعة.' }, reviewStatus: 'approved', publicationStatus: 'published-demo', provenance: 'Original demonstration question' },
      { id: 'q-speed-2', version: 1, lessonId: 'lesson-motion-basics', skillId: 'skill-speed', difficulty: 'application', type: 'numeric', promptAr: 'قطعت حافلة 240 مترًا في 30 ثانية. اكتب السرعة بالمتر/ثانية.', promptEn: 'A bus covers 240 m in 30 s. Enter the speed in metres/second.', correctAnswer: 8, tolerance: 0.01, unitAr: 'م/ث', unitEn: 'm/s', explanationAr: '240 ÷ 30 = 8 م/ث.', explanationEn: '240 ÷ 30 = 8 m/s.', numericFeedback: 'اكتب المسافة ÷ الزمن، ثم تحقّق من الوحدة.', reviewStatus: 'approved', publicationStatus: 'published-demo', provenance: 'Original demonstration question' },
      { id: 'q-speed-3', version: 1, lessonId: 'lesson-motion-basics', skillId: 'skill-speed', difficulty: 'transfer', type: 'multiple-choice', promptAr: 'سيارتان قطعتا المسافة نفسها. الأولى استغرقت نصف زمن الثانية. ماذا نستنتج؟', promptEn: 'Two cars cover the same distance. The first takes half the time of the second. What follows?', choicesAr: ['سرعتهما متساوية', 'الأولى أسرع بمرتين', 'الثانية أسرع بمرتين', 'لا يمكن المقارنة'], choicesEn: ['Same speed', 'First is twice as fast', 'Second is twice as fast', 'Cannot compare'], correctAnswer: '1', explanationAr: 'عند ثبات المسافة، تقليل الزمن إلى النصف يضاعف السرعة.', explanationEn: 'For equal distance, halving the time doubles speed.', reviewStatus: 'approved', publicationStatus: 'published-demo', provenance: 'Original demonstration question' },
      { id: 'q-graph-1', version: 1, lessonId: 'lesson-graphs', skillId: 'skill-graphs', difficulty: 'core', type: 'multiple-choice', promptAr: 'ماذا يعني خط أفقي في رسم المسافة–الزمن؟', promptEn: 'What does a horizontal line on a distance–time graph mean?', choicesAr: ['سرعة ثابتة', 'الجسم متوقف', 'تسارع كبير', 'عودة للخلف'], choicesEn: ['Constant speed', 'Object stopped', 'High acceleration', 'Moving backwards'], correctAnswer: '1', explanationAr: 'المسافة لا تتغير مع الزمن، لذلك الجسم متوقف.', explanationEn: 'Distance does not change over time, so the object is stopped.', reviewStatus: 'approved', publicationStatus: 'published-demo', provenance: 'Original demonstration question' },
      { id: 'q-graph-2', version: 1, lessonId: 'lesson-graphs', skillId: 'skill-graphs', difficulty: 'application', type: 'multiple-choice', promptAr: 'أي خط يعبّر عن جسم أسرع في رسم المسافة–الزمن؟', promptEn: 'Which line represents a faster object on a distance–time graph?', choicesAr: ['الأقل ميلًا', 'الأكثر ميلًا', 'الأفقي', 'كلها متساوية'], choicesEn: ['Less steep', 'Steeper', 'Horizontal', 'All equal'], correctAnswer: '1', explanationAr: 'الميل الأكبر يعني قطع مسافة أكبر في الزمن نفسه.', explanationEn: 'A steeper slope means more distance in the same time.', reviewStatus: 'approved', publicationStatus: 'published-demo', provenance: 'Original demonstration question' },
      { id: 'q-graph-3', version: 1, lessonId: 'lesson-graphs', skillId: 'skill-graphs', difficulty: 'transfer', type: 'multiple-choice', promptAr: 'خط يبدأ شديد الميل ثم يصبح أفقيًا. ما القصة الأدق؟', promptEn: 'A line starts steep then becomes horizontal. What is the best story?', choicesAr: ['تحرّك سريعًا ثم توقف', 'بقي متوقفًا', 'تحرك ببطء ثم أسرع', 'عاد إلى البداية'], choicesEn: ['Moved fast then stopped', 'Stayed stopped', 'Moved slowly then sped up', 'Returned to start'], correctAnswer: '0', explanationAr: 'الميل الشديد حركة سريعة، ثم ثبات المسافة يعني التوقف.', explanationEn: 'The steep section is fast movement; unchanged distance then means stopped.', reviewStatus: 'approved', publicationStatus: 'published-demo', provenance: 'Original demonstration question' },
      { id: 'q-boss-1', version: 1, lessonId: null, unitId: 'unit-motion', skillId: 'skill-speed', difficulty: 'core', type: 'numeric', promptAr: 'قطع جسم 60 مترًا في 12 ثانية. ما سرعته؟', promptEn: 'An object covers 60 m in 12 s. What is its speed?', correctAnswer: 5, tolerance: 0.01, unitAr: 'م/ث', unitEn: 'm/s', explanationAr: '60 ÷ 12 = 5 م/ث.', explanationEn: '60 ÷ 12 = 5 m/s.', reviewStatus: 'approved', publicationStatus: 'published-demo', provenance: 'Original demonstration question' },
      { id: 'q-boss-2', version: 1, lessonId: null, unitId: 'unit-motion', skillId: 'skill-graphs', difficulty: 'application', type: 'multiple-choice', promptAr: 'تحرك جسم من 0 إلى 30 م خلال 5 ثوانٍ ثم ثبتت المسافة 3 ثوانٍ. ماذا حدث؟', promptEn: 'An object moves from 0 to 30 m in 5 seconds, then distance stays fixed for 3 seconds. What happened?', choicesAr: ['تحرك ثم توقف', 'توقف ثم تحرك', 'عاد للخلف', 'تسارع طوال الوقت'], choicesEn: ['Moved then stopped', 'Stopped then moved', 'Moved backwards', 'Accelerated throughout'], correctAnswer: '0', explanationAr: 'تغيرت المسافة أولًا، ثم لم تتغير خلال الثواني الثلاث.', explanationEn: 'Distance changed first, then stayed unchanged for three seconds.', reviewStatus: 'approved', publicationStatus: 'published-demo', provenance: 'Original demonstration question' },
      { id: 'q-boss-3', version: 1, lessonId: null, unitId: 'unit-motion', skillId: 'skill-speed', difficulty: 'transfer', type: 'multiple-choice', promptAr: 'طالب قال: «الجسم الذي يقطع مسافة أكبر يكون دائمًا أسرع». ما أفضل رد؟', promptEn: 'A student says, “The object covering more distance is always faster.” Best response?', choicesAr: ['صحيح دائمًا', 'نحتاج معرفة الزمن أيضًا', 'نحتاج معرفة الكتلة', 'المسافة لا علاقة لها'], choicesEn: ['Always true', 'We also need the time', 'We need the mass', 'Distance is irrelevant'], correctAnswer: '1', explanationAr: 'السرعة تعتمد على المسافة والزمن معًا؛ قد تستغرق المسافة الأكبر وقتًا أطول.', explanationEn: 'Speed depends on both distance and time; a longer distance may take longer.', reviewStatus: 'approved', publicationStatus: 'published-demo', provenance: 'Original demonstration question' },
    ],
    attempts: [], mastery: [], reviews: [], lessonCompletions: [], bossAttempts: [],
    ledger: [{ id: 'seed-coins', userId: 'student-1', amount: 160, currency: 'COIN', reason: 'DEMO_STARTING_BALANCE', reference: 'demo-seed', idempotencyKey: 'seed:student-1:coins', ruleVersion: 'economy-mvp-1', createdAt: new Date().toISOString() }],
    shopItems: [
      { id: 'avatar-explorer', type: 'avatar', price: 0, active: true, nameAr: 'المستكشف', nameEn: 'Explorer', icon: '🧭', color: '#8b5cf6' },
      { id: 'outfit-orbit', type: 'outfit', price: 120, active: true, nameAr: 'بدلة المدار', nameEn: 'Orbit suit', icon: '🪐', color: '#4f46e5' },
      { id: 'companion-fox', type: 'companion', price: 180, active: true, nameAr: 'ثعلب الفِكر', nameEn: 'Clever fox', icon: '🦊', color: '#f97316' },
      { id: 'background-lab', type: 'background', price: 240, active: true, nameAr: 'مختبر النجوم', nameEn: 'Star lab', icon: '🔭', color: '#0891b2' },
    ],
    purchases: [], inventory: [{ userId: 'student-1', itemId: 'avatar-explorer', acquiredAt: new Date().toISOString(), source: 'starter' }],
    assignments: [{ id: 'assignment-1', classId: 'class-1', teacherId: 'teacher-1', lessonId: 'lesson-motion-basics', titleAr: 'ابدأ بأساسيات الحركة', titleEn: 'Start with motion basics', dueAt: null, createdAt: new Date().toISOString() }],
    audit: [], idempotency: [],
  };
}
